#!/usr/bin/env python3

import sys, logging
from helpers import read_ignore_comments, selenium_driver
from config import config
import shops, choice_strategies

def buy(shop, choice_strategy, queries):
  for query in queries:
    logging.info(f"Current: {query}")
    products = choice_strategy(shop, query)
    for product in products:
      product.add_to_cart()

  shop.go_to_cart()
  print("Finish the order and then press Enter")
  input()

logging.basicConfig(level=logging.INFO, format="%(message)s")

shop_name, strategy_name, queries_file = sys.argv[1:]
shop_class = getattr(shops, shop_name)
strategy = getattr(choice_strategies, strategy_name)
queries = read_ignore_comments(queries_file)

with selenium_driver(config["selenium"]["path"]) as driver:
  driver.maximize_window()
  shop = shop_class(driver)
  buy(shop, strategy, queries)
